#!/bin/bash
Color_Off='\033[0m'       # Text Reset
# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

count=0
cd /var/cpanel/users
for user in *
do
if [[ $user != "system" ]]
then
inodes=$(whmapi1 accountsummary user="$user" | grep "inodesused: " | awk '{print $2}')
printf "$Yellow $user $Color_Off : $Red $inodes $Color_Off\n"
count=`expr $count + 1`
fi
done
##echo $count
